### ISSUE TITLE
it is possible to have Senic Gira Philips friends Blueprint?

### ISSUE THREAD

**Issue by platini76** [Sian-Lee-SA/Home-Assistant-Switch-Manager#104]
I have a switch like this 
https://www.zigbee2mqtt.io/devices/PTM_215Z.html#enocean-ptm%2520215z
connected with zigbee2mqtt, can you please create a blueprint for this button?
thanks
davide

**Comment by Sian-Lee-SA** [comment]
You will need to either wait until someone with the device creates the blueprint or create it yourself

**Comment by platini76** [comment]
I have no idea how to create... can I give you value and you can help me in this?

**Comment by Sian-Lee-SA** [comment]
https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager#blueprints will give you all the information you would need to make a blueprint... There are examples down the bottom... Review and copy another similar blueprint if you want a quicker start.

**Comment by platini76** [comment]
I really understand nothing ... but ok.. thnaks
thanks anyway

**Comment by platini76** [comment]
look if they are correct please... 
[Archivio.zip](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/files/10845550/Archivio.zip)
