### ISSUE TITLE
aqara opple 3x2 hold

### ISSUE THREAD

**Issue by Dunkelschunkel** [Sian-Lee-SA/Home-Assistant-Switch-Manager#108]
Hi @Sian-Lee-SA ,

I am observing a different hold as well as hold(release) behavior with the above device.
Long pressing gives 1 hold and after 2-3 seconds a hold release. Increasing a brightness for example results in just one execution of the service 

In your video you are mentioning hold should be repeated

I can see both the button hold and automatically after 3 seconds the hold release in zigbee2mqtt as "action"

A hold until released would be great

**Comment by Sian-Lee-SA** [comment]
That is entirely dependent on how your device is designed and whether it repeats a hold or not. I think I also mention this in the video. You would need to come up with your own logic within the sequence to give the result you're after.
