### ISSUE TITLE
Dot-menu partially hidden

### ISSUE THREAD

**Issue by Dunkelschunkel** [Sian-Lee-SA/Home-Assistant-Switch-Manager#109]
Hi @Sian-Lee-SA,

I just love your integration so much and I wished more people know about it. Even with just one switch at the moment i am still amazed at what you've created to ease home assistant automation. 
All that said, there is a rather obnoxious bug with the dot menu from which you can go to your variables or start debug functions. On smaller screen and on mobile this menu is hidden by the automation part of your integration. Rather annoying. 
![grafik](https://user-images.githubusercontent.com/83595637/224486592-442a1bda-b209-451a-b8df-dc48e7cb3625.png)
Screenshot tells the story.

Greetings from around the world.
Dunkelschunkel

**Comment by Sian-Lee-SA** [comment]
I'll have a look into that but as a side note the device image should be creating a viable space between the header and sequence. In your screenshot, it seems there's no image for the device or the height is extremely small.

**Comment by Sian-Lee-SA** [comment]
This is the smallest image of a blueprint in regards to height:width ratio and displays fine

![Screenshot_20230311-234831](https://user-images.githubusercontent.com/11685433/224486903-d73753b3-50fc-4691-8008-020c8f675f7b.png)

**Comment by Dunkelschunkel** [comment]
Just expand the automation and scroll them to where the switch image is in your screenshot

Mar 11, 2023 2:19:40 PM Sian ***@***.***>:

**Comment by Sian-Lee-SA** [comment]
Fixed in version [1.0.4](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/releases/tag/v1.0.4)

**Comment by Dunkelschunkel** [comment]
@Sian-Lee-SA I tested it and it is beautiful. thanks for fixing it
