### ISSUE TITLE
Feature request: Global presets

### ISSUE THREAD

**Issue by proggprod** [Sian-Lee-SA/Home-Assistant-Switch-Manager#118]
Most of the light switches in my house are the same brands and models. Most of the time my switches are used for lights and not other automations or actions.

Can you add ‘Presets’ that can be assigned to multiple switches? This way I only need to program the default behaviour for each switch type that I have, instead of having to recreate a switch for each and every switch

**Comment by proggprod** [comment]
Thanks for the reply.

I'm brand new to HA, just installed it a few days ago, coming from openHAB. Can you point me in the right direction to understand and use variables and scripts as you descriibe? It might be close to what I'm trying to do.
Maybe I need an addon for your addon.
In my previous iteration of something like this, I defined the full behaviour of a light switch for a light, including switch model, up/down presses, all the multi presses, and holds etc. Then I can simply attach a light to a switch and every behaviour is enabled. 

![image](https://user-images.githubusercontent.com/81530084/233106351-60885faa-ed87-4e94-a1cc-3ccbfae5633d.png)
![image](https://user-images.githubusercontent.com/81530084/233106502-2b08f3d6-2a00-4aeb-9b92-313d6f4b2e4e.png)

Do you think I could achieve something like this with the method you suggested with scripts and variables?

**Comment by Sian-Lee-SA** [comment]
As you might be aware, Home Assistant utilises a sequence of actions for their automations and scripts. Scripts are generally used for a bunch of sequences that re reused over and over. Switch Manager uses these same techniques but contains them away from automations and entities. Once you familiarise yourself with Home Assistant's way of executing automations etc then it should become more clear.

I am not familiar with OpenHab so I can't describe the differences nor can I advise on how OpenHab works in comparison to Home Assistant.

But generally speaking, you can add Jinja code in your sequences [Templating](https://www.home-assistant.io/docs/configuration/templating/). if you have some kind of special sequence that you want to reuse, then you would create a [Script](https://www.home-assistant.io/integrations/script/) then pass in variables. You can call this script from adding it to the sequence...

Switch Manager also provides variables which you can define from the menu in the top right, You can then access that variable with Jinja... So if you have a switch where they do the same thing but target something different. then you can simply copy the yaml from the first switch then paste into the yaml of the second switch, you could also just change the switch variable which then changes the target based on an entity or whatever you wish.

**Comment by Sian-Lee-SA** [comment]
To toggle a light, just use the light.toggle service then pick the entities or area that you want the toggle to affect

**Comment by Sian-Lee-SA** [comment]
Added copy from in v1.2.0
