### ISSUE TITLE
Feature Request: Action layers

### ISSUE THREAD

**Issue by D3SL** [Sian-Lee-SA/Home-Assistant-Switch-Manager#120]
I was thinking about how switch manager feels just like setting up a game controller and realised that the similarities can go both ways. When setting up a steam controller you can define multiple "layers" with different settings or bindings as well as when they're activated. A very common example is changing bindings, gyroscope settings, or sensitivity when a trigger is partially depressed.

I feel like this would intuitively fit with Switch Manager. 

For example I have a styrbar near my bed configured as a (basic) remote control for my media center. It would be _fantastic_ if I could switch to a different set of controls to do other things with it, like turn off all the lights if I forgot something and don't want to get out of bed.

I think all that would be needed are the layers themselves, a next/previous control, and a programmatic way to directly active a given layer for a given switch. With that users could use existing systems like automations or node-red if they want state based controls, such as in my case having a media controller if kodi's active or home remote if it's not.

**Comment by Sian-Lee-SA** [comment]
This is already possible with switch variables or the wwitch button state variable

The following video will get you started
https://youtu.be/m2Rlobvo5cI?t=801
