### ISSUE TITLE
- Feature request - Duplicate buttons within switches! - slightly different requirement than implemented

### ISSUE THREAD

**Issue by bleughb** [Sian-Lee-SA/Home-Assistant-Switch-Manager#132]
It's quite common for a switch with multiple buttons / functions will be controlling only one device.
maybe Lamp on / off / brightness up / down 
so i'd like to copy the entities off the first button

For example - I've created a switch...
Programmed up the first button........

![image](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/36889022/cb136704-27e1-462f-b7f4-40d1f96b24fe)

Now for the second function 'Click 2x', i'd like to 'copy first' or something similar
where the edit YAML is...

![image](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/36889022/6197bb4f-1455-4a77-a395-16cfd642d048)

this saves repeatedly selecting 'device', 'tall lamp'...for all 5 of the functions on this switch
and i'm sure it'll save repeately selecting / populating the other 'actions' that are possible - as often, every button has a similar action that will need minor changing 

it won't help for everyone, but it'll reduce the amount of button clicks / menu selections needed for a fair chunk of users

For example, when the user selects 'click2x', HOLD, ROTATE RIGHT, ROTATE LEFT - it's default page is blank and just has 'add action'
a 'duplicate previous' or 'duplicate 'select button to duplicate' context menu option like below
would populate each button with whatever was on the previous button

![image](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/36889022/592ca37f-18df-4c44-9d3b-06ba96ca02a0)

Hope that all makes sense, thankyou for the hard work on this, I'm hoping I can assist more as i learn more

**Comment by Sian-Lee-SA** [comment]
Just use variables and set the device as a variable. then choose your sequence for each button action or just copy the yaml from one action to the next. Then just use the copy from option for another switch which does the same thing but for different device which you can then simply change the variable.
