### ISSUE TITLE
new blueprint not showing up

### ISSUE THREAD

**Issue by imbackniantic** [Sian-Lee-SA/Home-Assistant-Switch-Manager#149]
Hi, I'm interested in using the moes knob, i've seen you merged the request with the file (Moes Smart Knob AKA ERS-10TZBVK-AA) i've downloaded it waiting for your official update of the versione. I've added the 2 files (pngl and yaml) in the directory but is not showing up as a choice in the switch manager, how can I solve?

**Comment by Sian-Lee-SA** [comment]
Just posted update with the blueprint you're after... Just note making or copying blueprints needs to go into config/blueprints/switch_manager folder and not in the custom_components folder
