### ISSUE TITLE
[Feature Request] Parity with Home Assistant Automation GUI

### ISSUE THREAD

**Issue by zimmra** [Sian-Lee-SA/Home-Assistant-Switch-Manager#163]
Home Assistant has added many new features to their Automation GUI that are not present here, such as:

- Cut/Copy/Paste of Triggers, Conditions, and Actions/Services
- Automatic filtering of entities by corresponding service call's domain

I love Switch Manager, but because of these added conveniences I find myself creating sequences as scripts outside of Switch Manager and invoking those instead of using Switch Manager entirely.

**Comment by JigSawFr** [comment]
Support this !
