### ISSUE TITLE
Blueprint for Philips HUE Wall Switch Module - MQTT

### ISSUE THREAD

**Issue by GB-1972** [Sian-Lee-SA/Home-Assistant-Switch-Manager#168]
Hi there,
this is not really an issue, but I don't know where to post this instead.
Here is my Blueprint for HUE Wall Switch Module for Zigbee2MQTT.
Maybe you want to integrate it.

[zigbee2mqtt-philips-hue-wall-switch-module.yaml.txt](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/files/12573726/zigbee2mqtt-philips-hue-wall-switch-module.yaml.txt)
![zigbee2mqtt-philips-hue-wall-switch-module](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/133803371/6c33b641-edb9-4969-8950-dd7f20ac5242)

**Comment by Sian-Lee-SA** [comment]
You will need to fork then create a PR. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork
