### ISSUE TITLE
blueprints(zha-aqara-h1-rotary-dimmer)

### ISSUE THREAD

**Issue by yarafie** [Sian-Lee-SA/Home-Assistant-Switch-Manager#171]
Getting the below error in Home Assistant.
I don't use it but nonetheless its an error.

Logger: custom_components.switch_manager.const
Source: custom_components/switch_manager/__init__.py:61
Integration: Switch Manager (documentation, issues)
First occurred: 5:59:08 AM (1 occurrences)
Last logged: 5:59:08 AM

switch_manager blueprints(zha-aqara-h1-rotary-dimmer) Single button blueprints should not have x, y, width, height or deptg

**Comment by Sian-Lee-SA** [comment]
Yes, this has already been noted to the author https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/pull/162

**Comment by yarafie** [comment]
Thanks did a search before i posted must have missed it

**Comment by Sian-Lee-SA** [comment]
All good, it was in the PR thread so I wouldn't expect you to search there anyways but nice to know you did a search first which many people fail to do generally. Thanks
