### ISSUE TITLE
Rotary dimmer error message

### ISSUE THREAD

**Issue by jlabataille** [Sian-Lee-SA/Home-Assistant-Switch-Manager#172]
I find the following error frequently in my log file:
`switch_manager blueprints(zha-aqara-h1-rotary-dimmer) Single button blueprints should not have x, y, width, height or d
`

I am using version1.3 in Home Assistant 2023.10.0b2, Supervisor 2023.09.3, Operating System 10.5, Frontend 20230926.0)

**Comment by Sian-Lee-SA** [comment]
closing as duplicate https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/171
