### ISSUE TITLE
Device IDs instead of names

### ISSUE THREAD

**Issue by avoncharles** [Sian-Lee-SA/Home-Assistant-Switch-Manager#173]
When adding an action to a button, after finding the correct device, actions are shown with Device IDs instead of names. See attached. 
![Screenshot_20231003_202027_Home Assistant](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/94280491/c6ccd339-fccd-4faa-9411-68a86b64ec3b)

**Comment by EkoeNi** [comment]
Hi,
I can confirm this issue on 1.3.1 (installed with HACS)
When i configure a HUE Dimmer, i see ids instead of names. The issue doesn't occur on Home Assistant automation page.
Thanks
