### ISSUE TITLE
Support for xiaomi switch

### ISSUE THREAD

**Issue by tontondic1980** [Sian-Lee-SA/Home-Assistant-Switch-Manager#18]
Hi,
Possible to add support for xiaomi switch ?
I have the blueprint for all he xiaomi switch.
`blueprint:
  name: Aqara Buttons All-In-One [Zigbee2MQTT]
  description: 'All-In-One package for Aqara Switches.

    Supports: WXKG11LM, WXKG12LM, WXKG03LM, WXKG06LM, WXKG07LM, WXKG02LM, QBKG03LM,
    QBKG04LM, QBKG11LM, QBKG12LM, QBKG21LM, QBKG22LM, QBKG25LM, etc..).

    Does not supports Opple.

    Some actions may be unsupported by your switch. Check the available actions of
    your device on zigbee2mqtt.io.

    '
  domain: automation
  input:
    action_sensor:
      name: Action Sensor
      description: Zigbee2mqtt action sensor
      selector:
        entity:
          integration: mqtt
          domain: sensor
          multiple: false
    single_action:
      name: Single click
      description: Simple clic pour interrupteur 1 bouton
      default: []
      selector:
        action: {}
    double_action:
      name: Double Click
      description: Double clic pour interrupteur 1 bouton
      default: []
      selector:
        action: {}
    triple_action:
      name: Triple Clic
      description: Triple click for devices with one button
      default: []
      selector:
        action: {}
    quadruple_action:
      name: Quadruple Click
      description: Triple click for devices with one button
      default: []
      selector:
        action: {}
    hold_action:
      name: Hold Action
      description: Hold action for devices with one button
      default: []
      selector:
        action: {}
    release_action:
      name: Release Action
      description: Release action for devices with one button
      default: []
      selector:
        action: {}
    shake_action:
      name: Shake Action
      description: Shake action for devices with one button
      default: []
      selector:
        action: {}
    single_left_action:
      name: Single Left Click
      description: Left click for devices with multiple buttons
      default: []
      selector:
        action: {}
    double_left_action:
      name: Double Left Click
      description: Double left click for devices with multiple buttons
      default: []
      selector:
        action: {}
    triple_left_action:
      name: Triple Left Click
      description: Triple left click for devices with multiple buttons
      default: []
      selector:
        action: {}
    hold_left_action:
      name: Hold Left Action
      description: Hold left action for devices with multiple buttons
      default: []
      selector:
        action: {}
    release_left_action:
      name: Release Left Action
      description: Release left action for devices with multiple buttons
      default: []
      selector:
        action: {}
    single_center_action:
      name: Single Center Click
      description: Center click for devices with three buttons
      default: []
      selector:
        action: {}
    double_center_action:
      name: Double Center Click
      description: Double center click for devices with three buttons
      default: []
      selector:
        action: {}
    triple_center_action:
      name: Triple Center Click
      description: Triple center click for devices with three buttons
      default: []
      selector:
        action: {}
    hold_center_action:
      name: Hold Center Action
      description: Hold center action for devices with three buttons
      default: []
      selector:
        action: {}
    release_center_action:
      name: Release Center Action
      description: Release center action for devices with three buttons
      default: []
      selector:
        action: {}
    single_right_action:
      name: Single Right Click
      description: Right click for devices with multiple buttons
      default: []
      selector:
        action: {}
    double_right_action:
      name: Double Right Click
      description: Double right click for devices with multiple buttons
      default: []
      selector:
        action: {}
    triple_right_action:
      name: Triple Right Click
      description: Triple right click for devices with multiple buttons
      default: []
      selector:
        action: {}
    hold_right_action:
      name: Hold Right Action
      description: Hold right action for devices with multiple buttons
      default: []
      selector:
        action: {}
    release_right_action:
      name: Release Right Action
      description: Release right action for devices with multiple buttons
      default: []
      selector:
        action: {}
    single_both_action:
      name: Single Both Click
      description: Both click for devices with multiple buttons
      default: []
      selector:
        action: {}
    double_both_action:
      name: Double Both Click
      description: Double both click for devices with multiple buttons
      default: []
      selector:
        action: {}
    triple_both_action:
      name: Triple Both Click
      description: Triple both click for devices with multiple buttons
      default: []
      selector:
        action: {}
    hold_both_action:
      name: Hold Both Action
      description: Hold both action for devices with multiple buttons
      default: []
      selector:
        action: {}
    release_both_action:
      name: Release Both Action
      description: Release both action for devices with multiple buttons
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/aqara-buttons-all-in-one-zigbee2mqtt/268717
mode: parallel
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input 'action_sensor'
action:
- variables:
    command: '{{ trigger.to_state.attributes.action if trigger.to_state.state == "" else trigger.to_state.state }}'
- choose:
  - conditions: '{{ command == ''single'' }}'
    sequence: !input single_action
  - conditions: '{{ command == ''double'' }}'
    sequence: !input double_action
  - conditions: '{{ command == ''triple'' }}'
    sequence: !input triple_action
  - conditions: '{{ command == ''quadruple'' }}'
    sequence: !input quadruple_action
  - conditions: '{{ command == ''hold'' }}'
    sequence: !input hold_action
  - conditions: '{{ command == ''release'' }}'
    sequence: !input release_action
  - conditions: '{{ command == ''shake'' }}'
    sequence: !input shake_action
  - conditions: '{{ command == ''single_left'' }}'
    sequence: !input single_left_action
  - conditions: '{{ command == ''double_left'' }}'
    sequence: !input double_left_action
  - conditions: '{{ command == ''triple_left'' }}'
    sequence: !input triple_left_action
  - conditions: '{{ command == ''hold_left'' }}'
    sequence: !input hold_left_action
  - conditions: '{{ command == ''release_left'' }}'
    sequence: !input release_left_action
  - conditions: '{{ command == ''single_center'' }}'
    sequence: !input single_center_action
  - conditions: '{{ command == ''double_center'' }}'
    sequence: !input double_center_action
  - conditions: '{{ command == ''triple_center'' }}'
    sequence: !input triple_center_action
  - conditions: '{{ command == ''hold_center'' }}'
    sequence: !input hold_center_action
  - conditions: '{{ command == ''release_center'' }}'
    sequence: !input release_center_action
  - conditions: '{{ command == ''single_right'' }}'
    sequence: !input single_right_action
  - conditions: '{{ command == ''double_right'' }}'
    sequence: !input double_right_action
  - conditions: '{{ command == ''triple_right'' }}'
    sequence: !input triple_right_action
  - conditions: '{{ command == ''hold_right'' }}'
    sequence: !input hold_right_action
  - conditions: '{{ command == ''release_right'' }}'
    sequence: !input release_right_action
  - conditions: '{{ command == ''single_both'' }}'
    sequence: !input single_both_action
  - conditions: '{{ command == ''double_both'' }}'
    sequence: !input double_both_action
  - conditions: '{{ command == ''triple_both'' }}'
    sequence: !input triple_both_action
  - conditions: '{{ command == ''hold_both'' }}'
    sequence: !input hold_both_action
  - conditions: '{{ command == ''release_both'' }}'
    sequence: !input release_both_action
`

**Comment by Sian-Lee-SA** [comment]
This blueprint references multiple switches as one. I would need something more specific to the actual switch you need. Or if you want to try creating the blueprint, it's pretty easy ;-). I also noticed that blueprint references a state as the trigger, Switch Manager can use MQTT directly though and is the better approach.

**Comment by tontondic1980** [comment]
If you can create the blueprint for the Xiaomi [WXKG07LM], it will be great ! Thanks
`name: Xiaomi 2 boutons
service: Zigbee2MQTT
event_type: mqtt
mqtt_topic_format: zigbee2mqtt/+/action
buttons:
   -actions:
      - title: tap
        conditions:
          - key: payload
            value: 1_single
      - title: double tap
        conditions:
          - key: payload
            value: 1_double
      - title: hold
        conditions:
          - key: payload
            value: 1_long
  -actions:
      - title: tap
        conditions:
          - key: payload
            value: 2_single
      - title: double tap
        conditions:
          - key: payload
            value: 2_double
      - title: hold
        conditions:
          - key: payload
            value: 2_long`

**Comment by tontondic1980** [comment]
And I find that your integration is great, it's more simple than an automation.

**Comment by Sian-Lee-SA** [comment]
Added to v0.2.1. Hope it's correct as I can't test ;)

**Comment by tontondic1980** [comment]
Infortunately, the left button is perfect, but the right doesn't work.

**Comment by Sian-Lee-SA** [comment]
What about the double press?

**Comment by Sian-Lee-SA** [comment]
Because I can't test, if you can listen to the mqtt for your device then let me know the value then I can update... Just goto the mqtt integration and choose configure... In listen to a topic just enter zigbee2mqtt/+/action and start listening.. Push the right button and you will get the value. Once I have that then I can add to the blueprint.

Currently I've referenced the doc https://www.zigbee2mqtt.io/devices/WXKG07LM.html and used the values they stated there so not sure why it wouldn't be those values.

**Comment by tontondic1980** [comment]
or That
`event_type: state_changed
data:
  entity_id: sensor.interrupteur_double_rdc_escalier_action
  old_state:
    entity_id: sensor.interrupteur_double_rdc_escalier_action
    state: right
    attributes:
      action: right
      battery: 100
      device_temperature: 19
      linkquality: 123
      power_outage_count: 41
      voltage: 3025
      icon: mdi:gesture-double-tap
      friendly_name: Interrupteur double rdc action
    last_changed: "2022-12-20T08:12:01.817718+00:00"
    last_updated: "2022-12-20T08:12:01.817718+00:00"
    context:
      id: 01GMQ9DVWSQPM2ER8JCCEQVCX0
      parent_id: null
      user_id: null
  new_state:
    entity_id: sensor.interrupteur_double_rdc_escalier_action
    state: ""
    attributes:
      action: ""
      battery: 100
      device_temperature: 19
      linkquality: 123
      power_outage_count: 41
      voltage: 3025
      icon: mdi:gesture-double-tap
      friendly_name: Interrupteur double rdc action
    last_changed: "2022-12-20T08:12:01.818004+00:00"
    last_updated: "2022-12-20T08:12:01.818004+00:00"
    context:
      id: 01GMQ9DVWT9ZDHGMDRWMS3D1YX
      parent_id: null
      user_id: null
origin: LOCAL
time_fired: "2022-12-20T08:12:01.818004+00:00"
context:
  id: 01GMQ9DVWT9ZDHGMDRWMS3D1YX
  parent_id: null
  user_id: null
`

**Comment by tontondic1980** [comment]
Message 0 reçu sur zigbee2mqtt/Interrupteur double rdc/action à 09:17 :

right

QoS: 0 - Retain: false

**Comment by Sian-Lee-SA** [comment]
On second look I found the actual topic 5 lines down... for some strange reason they used right instead of single_right where left button is single_left... strange! could you please follow this up with double press and hold aswell as pushing both together single, double and hold.

**Comment by Sian-Lee-SA** [comment]
Also are you using the latest Zigbee2MQTT version...? as I would hate to integrate a device that has been changed in recent versions

**Comment by tontondic1980** [comment]
zigbeemqtt 1.28.4-1 the last

**Comment by Sian-Lee-SA** [comment]
Ok thats alright then... Not sure why their documentation is stating different values to the ones you're getting though. very frustrating when they do that

**Comment by tontondic1980** [comment]
Message 7 reçu sur zigbee2mqtt/Interrupteur double rdc/action à 09:21 :

both_long

QoS: 0 - Retain: false
Message 6 reçu sur zigbee2mqtt/Interrupteur double rdc/action à 09:21 :

both

QoS: 0 - Retain: false
Message 5 reçu sur zigbee2mqtt/Interrupteur double rdc/action à 09:21 :

right_long

QoS: 0 - Retain: false
Message 4 reçu sur zigbee2mqtt/Interrupteur double rdc/action à 09:21 :

left_long

QoS: 0 - Retain: false
Message 3 reçu sur zigbee2mqtt/Interrupteur double rdc/action à 09:21 :

right_double

QoS: 0 - Retain: false
Message 2 reçu sur zigbee2mqtt/Interrupteur double rdc/action à 09:21 :

left_double

QoS: 0 - Retain: false
Message 1 reçu sur zigbee2mqtt/Interrupteur double rdc/action à 09:21 :

right

QoS: 0 - Retain: false
Message 0 reçu sur zigbee2mqtt/Interrupteur double rdc/action à 09:21 :

left

QoS: 0 - Retain: false

**Comment by tontondic1980** [comment]
Yes, the left works

**Comment by Sian-Lee-SA** [comment]
Try the update

**Comment by Sian-Lee-SA** [comment]
Also sorry, I missed the comment where you stated you couldn't find listening event. I was referring to MQTT and not event but to listen to MQTT in Home Assistant, goto Settings -> Integrations then on there click the configure button for the MQTT integration... Just for future reference.

**Comment by tontondic1980** [comment]
My mistake, i've forgot but i have an automation for the left button.
So i have delete this automation.
And nothing works in switch manager for this 2 buttons.
I've see any differences and the blueprint before et after.

**Comment by Sian-Lee-SA** [comment]
I figured that might be the case about maybe you had something already hooked to that button... So you updated to version 0.2.2 and did you set the MQTT topic in the top right to `zigbee2mqtt/Interrupteur double rdc/action`?

**Comment by Sian-Lee-SA** [comment]
And also make sure you restart Home Assistant when you update Switch Manager

**Comment by tontondic1980** [comment]
Yes, version 0.2.2, top right ok (top left no ?), and restart ok

**Comment by Sian-Lee-SA** [comment]
Sorry, yes top left... Been a long day lol

**Comment by tontondic1980** [comment]
I don't know why doesnt work....

**Comment by Sian-Lee-SA** [comment]
Same, it's challenging when I can't work with the device directly as it would be so much easier to tell whats going on... My next test would be to see if the discovery button picks up the MQTT topic once you push a button on the switch... Clear the MQTT topic field up in the top left then press the button next to it and then press a button on your switch. If it autofills the MQTT topic then it's definitely picking it up. I also assume you do have the MQTT integration setup in Home Assistant? I ask because the blueprint you referenced was referencing an entity and not MQTT almost like you have a 3rd party integration between Zigbee2MQTT and Home Assistant.

**Comment by Sian-Lee-SA** [comment]
I forgot to version bump last release... try 0.2.3... sorry

**Comment by tontondic1980** [comment]
Discovering ok, but error "identifier must not be empty"

**Comment by tontondic1980** [comment]
I've a broker mqtt

**Comment by Sian-Lee-SA** [comment]
Just make sure you updated to 0.2.3 and use the topic `zigbee2mqtt/Interrupteur double rdc/action`... It should work... The reason the blueprint didn't update before was because my integration didn't detect a version change which tells it to copy over blueprints if the versions are different from before..

**Comment by tontondic1980** [comment]
It works !!!

many thanks !

**Comment by Sian-Lee-SA** [comment]
Glad to hear... Closing now

**Comment by tontondic1980** [comment]
Perhaps, add the xiaomi mouvement detector ?
It's great to centralize all lights

**Comment by tontondic1980** [comment]
actually, I use this blueprint
`blueprint:
  name: Motion-activated Light
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/blueprints/motion_light.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

action:
  - alias: "Turn on the light"
    service: light.turn_on
    target: !input light_target
  - alias: "Wait until there is no motion from device"
    wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - alias: "Wait the number of seconds that has been set"
    delay: !input no_motion_wait
  - alias: "Turn off the light"
    service: light.turn_off
    target: !input light_target
`

**Comment by Sian-Lee-SA** [comment]
Due to the frustrations with trying to build blueprints without actually having the device, It's probably best to leave that up to the community or yourself to build the blueprints as we already experienced different values from the documentations and the values you were actually getting. this can be time consuming and miscommunicated. Switch Manager is also for switches and not motion sensors etc. that is more suited in the automation screen and doesn't belong in this integration

**Comment by tontondic1980** [comment]
Ok, thanks
