### ISSUE TITLE
Service 'Light: Toggle' does not show targets

### ISSUE THREAD

**Issue by hrw** [Sian-Lee-SA/Home-Assistant-Switch-Manager#180]
I installed Switch Manager to simplify handling all switches in my HA setup. Now pressing button in one room changes lights in the other room...

![Screenshot_20231105_231042](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/185508/bd682c77-0f10-44f5-b62d-1df654e48055)

Because 'Targets' option lost all data:

![Screenshot_20231105_230510](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/185508/3a5fc381-f349-49e9-a569-06b54757d0ea)

Yaml:

```yaml
- service: light.toggle
  data: {}
  target:
    area_id: sypialnia
```

New automation dialog shows 'Targets' properly and allows to select areas:

![Screenshot_20231105_230936](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/185508/15b70c08-2947-4069-8d20-227e02a816a5)

Looks like I have to do most of automations again from scratch ;(

**Comment by hrw** [comment]
In "Sypialnia" area I have two devices: a bulb and remote.

![Screenshot_20231105_231155](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/185508/e7f3617c-421d-4df2-b623-040f433e7a93)

**Comment by Sian-Lee-SA** [comment]
I can't seem to replicate this, also the area id should be a string of hexadecimal characters (unique id).

![image](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/11685433/18351c8e-3d6e-4edb-9e8a-be5543c28ea1)

![image](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/assets/11685433/ab0e3fed-caef-4190-b46d-2db21d9036a0)

**Comment by hrw** [comment]
Here area_id are names, not hex ids.
