### ISSUE TITLE
Support for Homematic IP Switch (HMIP-WRC6)

### ISSUE THREAD

**Issue by MarcelW85** [Sian-Lee-SA/Home-Assistant-Switch-Manager#19]
Hi and thanks for your nice integration.

Is it possible to integrate the Homematic IP 6-Button Switch (HMIP-WRC6).

There is a working Blueprint from danielperna84.

https://github.com/danielperna84/custom_homematic/blob/devel/blueprints/automation/homematicip_local-actions-for-6-button.yaml

Thanks 

Marcel

**Comment by Sian-Lee-SA** [comment]
I've added the blueprint but can't test whether the buttons are in the right order. It's added to the repo but not as a release yet. If you want, just copy the blueprint files from custom_components/switch_manager/blueprints to your home assistant config directory

**Comment by MarcelW85** [comment]
Thanks! 

I will test it today.

**Comment by MarcelW85** [comment]
It works perfectly.

Thank you very much.
