### ISSUE TITLE
[Feature Request] Add blueprint for Philips Hue Tap Dial in ZHA

### ISSUE THREAD

**Issue by niklas-fischer** [Sian-Lee-SA/Home-Assistant-Switch-Manager#207]
Dear Developers,

thanks for your hard work! Switch Manager is amazing :) I am writing to request the addition of a ZHA blueprint for the Philips Hue Tap Dial to the Home Assistant project. Currently, there exists a blueprint for the Hue Tap Dial, but it is limited to the Hue integration. I believe it would be highly beneficial to the Home Assistant community to have a ZHA-specific blueprint for this device.

**Context:**

- Home Assistant Version: 2024.1
- Switch Manager Version: v1.3.2

**Request:**
I kindly request the development team to create a ZHA blueprint for the Philips Hue Tap Dial. While a blueprint for the Hue integration exists, many users, including myself, prefer to use the ZHA integration for its flexibility and compatibility with various Zigbee devices.

**Comment by Sian-Lee-SA** [comment]
Blueprints are provided by the community and aren't developed by myself unless I own and tested the device. You're welcome to make a blueprint for it and share on this repo if you wish. Blueprints aren't hard
