### ISSUE TITLE
[Feature Request] Show location or other info

### ISSUE THREAD

**Issue by D3SL** [Sian-Lee-SA/Home-Assistant-Switch-Manager#208]
This may be somewhat redundant since Switch Manager names are independent of HA/Zigbee2mqtt, but it would be nice to support optional additional information such as location. Particularly if a switch could be tied to a Home Assistant device and pull information from there.

**Comment by Sian-Lee-SA** [comment]
I did contemplate adding things like battery level etc but it just isn't worth the hassle. Firstly this is a Home Assistant intgration and adding those things to the UI without any real interaction would be redundant and trying to reinvent the wheel. Secondly, there are just too many device types and sevices handling them which would need too much micro management. Personally, I find naming the switches to be descriptive which represents a room or specific object like the 3d printer etc.

**Comment by D3SL** [comment]
>Secondly, there are just too many device types and sevices handling them which would need too much micro management. 

That's unfortunate. I was hoping it would be possible to tie a Switch Manager entry to a given "Device" in Home Assistant and pull basic things like the friendly name or location. I guess if you could have done that easily you would have already, or even have gone one stop further and automatically populated any instances of supported devices.

>Personally, I find naming the switches to be descriptive which represents a room or specific object like the 3d printer etc.

I might try this. The separation from HA actually works in favor of user friendliness. Calling something "Kitchen LED dimmer and ceiling light toggle" in Switch Manager won't force me to type that out every time I want to refer to it in node-red or an automation.
