### ISSUE TITLE
IKEA Rodret (E2201) Button Hold Release not being handled

### ISSUE THREAD

**Issue by aryxton** [Sian-Lee-SA/Home-Assistant-Switch-Manager#214]
Rodret firmware: 1.0.47
Zigbee2mqtt: 1.35.3 commit: fe0742a

While trying to implement a dimming function with this remote I noticed that the messages being sent over to MQTT appear to have changed at some point as they don't align to what you have in the blueprint. I don't think it is a firmware change as this is the only firmware version ever released for the device (that I can tell) so it seems that zigbee2mqtt may have changed?

For initiating a hold, either button still sends their respective _**brightness_move_up**_ and _**brightness_move_down**_, but when you release either button the message sent is simply _**brightness_stop**_ and it doesn't differentiate between up and down.

The blueprint for this device expects _**brightness_stop_up**_ and _**brightness_stop_down**_ which are never sent.

I am new to your Switch Manager, but I didn't see a way to easily handle this in a blueprint. I was thinking maybe define a third button as Hold Release and handle it that way, but I am not sure if that is the best way.

an example from the log from zigbee2mqtt:
```
info 2024-02-23 18:40:14MQTT publish: topic 'zigbee2mqtt/Theater Remote', payload '{"action":"brightness_move_up","action_rate":83,"battery":90,"linkquality":66,"update":{"installed_version":16777287,"latest_version":16777287,"state":"idle"},"update_available":null}'
info 2024-02-23 18:40:14MQTT publish: topic 'zigbee2mqtt/Theater Remote', payload '{"action":"","battery":90,"linkquality":66,"update":{"installed_version":16777287,"latest_version":16777287,"state":"idle"},"update_available":null}'
info 2024-02-23 18:40:14MQTT publish: topic 'zigbee2mqtt/Theater Remote/action', payload 'brightness_move_up'
info 2024-02-23 18:40:15MQTT publish: topic 'zigbee2mqtt/Theater Remote', payload '{"action":"brightness_stop","battery":90,"linkquality":66,"update":{"installed_version":16777287,"latest_version":16777287,"state":"idle"},"update_available":null}'
info 2024-02-23 18:40:15MQTT publish: topic 'zigbee2mqtt/Theater Remote', payload '{"action":"","battery":90,"linkquality":66,"update":{"installed_version":16777287,"latest_version":16777287,"state":"idle"},"update_available":null}'
info 2024-02-23 18:40:15MQTT publish: topic 'zigbee2mqtt/Theater Remote/action', payload 'brightness_stop'
```

In addition, thank you for your work on this. It is excellently designed and well implemented.

Let me know if you want me to test anything with this device as I am unsure if you have access to one.

**Comment by fgibaux** [comment]
I'm getting the same issue with Ikea Styrbar E2002 (Firmware version 1.0.024) on Zigbee2MQTT version 1.36.0

switch manager debug log shows it's getting the following payloads:

- brightness_move_up (ok)
- brightness_stop (instead of brightness_stop_up)
- brightness_move_down (ok)
- brightness_stop (instead of brightness_stop_down)

the Zigbee2MQTT device documentation mentions the same: https://www.zigbee2mqtt.io/devices/E2001_E2002.html
