### ISSUE TITLE
[Feature Request] Manage multiple switches using a single configuration

### ISSUE THREAD

**Issue by dimatx** [Sian-Lee-SA/Home-Assistant-Switch-Manager#218]
First off, thanks for building this elegant and useful component. Glad to have just stumbled upon it. It will help replace many simple automations that I had to create to achieve the same functionality.

A feature request... I have several switches which share the same configuration, and it would be great to be able to have one configuration that can be assigned to multiple devices. For instance, I have an 2 x Aqara Oppel 3x2 switches in different locations with the exact same button mappings.

**Comment by dimatx** [comment]
Now that I've spotted the 'copy from' feature and this mostly addresses the use case I was after.

**Comment by mtvec** [comment]
I think this would still be a useful feature to have. I have a bunch of identical switches connected to different lights using identical configurations. It would be convenient to be able to change the configuration in one place and have all switches pick up on that.

What I imagine is having some kind of blueprint that includes most of the configuration. When adding a switch through this blueprint, I would just have to enter the light it should connect to and be done. Would something like this be possible?

**Comment by Sian-Lee-SA** [comment]
Just use copy from and switch variables

**Comment by mtvec** [comment]
I guess this wouldn't solve the centralized configuration point? That is, whenever I'd want to change a common configuration option, I'd have to use copy from on all switches again iiuc. This is probably not a huge issue but it could still be a nice-to-have feature to not have to do this.

**Comment by Sian-Lee-SA** [comment]
just use scripts for actions for things that need reference the same function, that's generally what scripts are made for. No point reinventing the wheel.

**Comment by mtvec** [comment]
Fair enough, that would indeed solve all use cases I can think of. Thanks!
