### ISSUE TITLE
entities are not shown by friendly name but entity ID

### ISSUE THREAD

**Issue by hesspoint** [Sian-Lee-SA/Home-Assistant-Switch-Manager#223]
Hi,

I want to assign an action to e.g. a light switch. In the visual editor I select "device" and then e.g. lamp1. and then in the dropdown the selection "turn on ..." Usually it would say the name of the entity there but instead it shows the id which makes it very hard to find the right one especially if a device has many different entities.

Btw if I select a service e.g. lights.turn_on and then click on the green choose entity pill then it shows the entities correctly with name.

Maybe it is just a quick fix.

Thanks a lot!

**Comment by Sian-Lee-SA** [comment]
This has something to do with Home Assistant fragmenting the language files which I've failed to track down when compiling from their source. Unfortunately I haven't had the time to look into it more. I also generally stay away from device actions as it's well known to be the less desired choice.

A future update would likely include the latest features from Home Assistant on how their sequence actions work and displayed. This also requires a bit of research on how it's been implemented and ensure I can compile without issue (not so easy). That should also hopefully fix the naming for devices

**Comment by hesspoint** [comment]
As far as I can see it was fixed in the last update.

Thanks a lot!
