### ISSUE TITLE
Not detected Shelly 1pm Gen3 events

### ISSUE THREAD

**Issue by cemilbrowne** [Sian-Lee-SA/Home-Assistant-Switch-Manager#227]
Hi all,

I'm not seeing proper detection of events from a Shelly 1pm Gen3.  It's definitely generating shelly.click events, but if I try the Shelly 1 blueprint, it never detects the device.  Adding device ID manually doesn't work either.

Listener example:

```event_type: shelly.click
data:
  device_id: 5e9ce12e65ccf4f4xxx
  device: shelly1pmminig3-xxx
  channel: 1
  click_type: single_push
  generation: 2
origin: LOCAL
time_fired: "2024-05-14T00:44:19.632089+00:00"
context:
  id: 01HXT8XC9GXBFFV1SA7HSCB1TB
  parent_id: null
  user_id: null```

**Comment by cemilbrowne** [comment]
For completeness, I've fixed this and will do a PR; the shelly integration doesn't work for this.

**Comment by Sian-Lee-SA** [comment]
Will close this as I can see your PR
