### ISSUE TITLE
Device Suggestion: Aqara Cube

### ISSUE THREAD

**Issue by hesspoint** [Sian-Lee-SA/Home-Assistant-Switch-Manager#233]
Hi,

Not sure if this is the correct way to suggest a new device but here it is:

I have the Aqara Cube https://www.aqara.com/en/product/cube/ and it was working fine with blueprints. But since I moved to Zigbee2MQTT none of the blueprints work for me

It would be awesome if you could support the Aqara Cube in Zigbee2MQTT. Of course it would also be great to support the newer T1 Pro version as well for other users that have that one.

Thank you!

**Comment by Sian-Lee-SA** [comment]
Feel free to create the blueprint and PR to this repo. Otherwise you'll have to wait for someone who owns the device and creates a PR for it.
