### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by Bertie57** [Sian-Lee-SA/Home-Assistant-Switch-Manager#234]
Hi - thanks for this add-on
I've just followed the instructions and installed it in HA [24.6.1].
When I click the link in the left-hand menu I just get a blank page. No buttons or anything.
Any suggestions?
Thanks

**Comment by Sian-Lee-SA** [comment]
You'll need to look at your logs and find any errors. Does the page show the Switch Manager title and version number?

**Comment by Sian-Lee-SA** [comment]
Also make sure you clear cache and do a hard refresh
