### ISSUE TITLE
Trying to cycle through group scenes on philips hue remote v2

### ISSUE THREAD

**Issue by nirurin** [Sian-Lee-SA/Home-Assistant-Switch-Manager#240]
I don't know where else to ask this, but I can't figure out how to get this working on Switch Manager as none of the options available seem to give me the right kind of logic options. 

I have found a place where I can set it so a specific scene gets activated, but not a way to cycle through multiple scenes. I thought I could set up a sequence of if/then statements, so that if scene A if active then buttong goes to Scene B etc etc. But none of the conditional statements let me see/use the 'current scene' information (as far as I can tell). 

Would appreciate some guidance. It may be that it can only be done via yaml files or something, but I don't have any idea of the syntax for those (which is why I'm using switch manager as it's a gui interface!)

**Comment by Sian-Lee-SA** [comment]
This question should be asked on the Home Assistant forum as it's not related to switch manager.  But my two cents is, put your scenes in a helper dropdown/select list. You can then use the select service to choose next and previous along with cycle. You can then use an automation on the list when changed and assign the scene selected.
