### ISSUE TITLE
New Switch Paulmann 501.34 zigbee2mqtt to add please

### ISSUE THREAD

**Issue by GerhardLang** [Sian-Lee-SA/Home-Assistant-Switch-Manager#241]
Hello.

Thank you for your Switch Manager and the documentation which allowed me to add my Paulmann switches.
Maybe you want to add this within the next release?
Files are included.
The picture and the according yaml file as text because I could not add the yaml.

Thank you.
![zigbee2mqtt-paulmann-switch-501-34](https://github.com/user-attachments/assets/060cdfe2-6431-4148-9566-90d298696833)
[zigbee2mqtt-paulmann-switch-501-34.txt](https://github.com/user-attachments/files/16432208/zigbee2mqtt-paulmann-switch-501-34.txt)

**Comment by Sian-Lee-SA** [comment]
Feel free to do a PR. Thanks

**Comment by ceear** [comment]
https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/pull/307
