### ISSUE TITLE
All actions shown as "unknown" and only YAML most

### ISSUE THREAD

**Issue by hesspoint** [Sian-Lee-SA/Home-Assistant-Switch-Manager#246]
Since recently when I define an action for whatever button on any device, I can define everything fine. Once I save and open again the action shows as "unknown" and I cannot switch to UI mode anymore.

![image](https://github.com/user-attachments/assets/c717c3c8-c599-4311-ab5c-f650c1e5fe4a)

I have the strong suspicion that it has something to do with services being renamed to actions in the latest HA release maybe?

HA 2024.8.1 and Switch Manager v1.3.4

Would be great if you could look into that.

**Comment by Sian-Lee-SA** [comment]
Technically it hasn't been renamed, it's just an alternative naming scheme. service still works just fine. Closing due to duplicate https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/244.
