### ISSUE TITLE
FR: Show visual feedback for pressed buttons in UI

### ISSUE THREAD

**Issue by cdjm** [Sian-Lee-SA/Home-Assistant-Switch-Manager#25]
Feature request:

Can you make the highlighted area flash a different color in the UI when the corresponding button is pressed?
This would add some useful feedback during creating blueprints or when configuring switches.

What do you think about this idea?

**Comment by Sian-Lee-SA** [comment]
I'm not sure what you mean, are you saying you want an animation to pulse the selected button? Why this isn't a bad idea and is simple to do, I'm concerned about implementing animations on a UI that could be on devices that struggle with animations and lacks GPU rendering etc. Even the pulsing on the discovery button I was skeptical about but was only active for a short time till it discovers the switch where an active button would be active while on the page the whole time.

**Comment by cdjm** [comment]
Kind of. I meant to pulse the overlay as a visual feedback when the button is physically pressed.

Maybe you can just switch the color for a few milliseconds instead of the pulse effect?
This should not harm the experience on weaker devices.

Regarding the pulse on the discovery button I find the "Press a button on your switch" sufficient as a clear feedback.
BTW: Is there a timeout for the discovery?

**Comment by Sian-Lee-SA** [comment]
Ahh ok, Thats something I can do. I'll have a look into it sometime. There's no timeout for the discovery, I thought about adding one but I can imagine people going around and hunting for their switch then pressing a button. Simply once the button is pushed or they leave the page then it stops listening

**Comment by cdjm** [comment]
That's great!

Speaking of going around and hunting I should probably start my hunt for my other switches to send you more blueprints then.

This component is really a great idea to manage switches in one place instead of creating numerous automations
and easy enough for me to contribute to.
Thank you.

BTW: I have some of these in-wall HomeMatic switches (i.e. HM-RC-2-PBU-FM) and some Shellys as well.
How do you want devices without a cover to be contributed? Any prefences?

**Comment by Sian-Lee-SA** [comment]
I just had a quick look at that device. You can just add the image but there doesn't need to be any button shapes etc if it's just one button also if it's just a one button device then it doesn't necessarily need to be top down view either. Alternatively you can choose to not add an image and it will default to a normal blue icon as the image but an image is preferred for user experience. I also appreciate your enthusiasm and willing to contribute.

Sometimes devices are the same but rebranded, I tend to try to figure out the original vendor then add the model number with the name to help differentiate the devices (sometimes this is a nightmare)

**Comment by Sian-Lee-SA** [comment]
This is now implemented in v0.2.5
