### ISSUE TITLE
Error in describing action: undefined is not iterable

### ISSUE THREAD

**Issue by DocGame69** [Sian-Lee-SA/Home-Assistant-Switch-Manager#252]
Since the update to 2.0, I can no longer edit my (very many) actions or create new ones.
As soon as I select a device, the following error message appears:
Error in describing action: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

What can that be?
![SwitchManager](https://github.com/user-attachments/assets/e0063902-cb19-4eb8-9981-23ddcdb31b03)

**Comment by Sian-Lee-SA** [comment]
Device selection for sequence has always been flaky. Infact, it just happened to be a coincidence that it started working on a previous version. But I did make a warning about this on the readme page and that device selection is unsupported. There is just something different in how HA has handled the structure of device selection compared to other sequence actions... It is also widely known that using the device action is a bad idea and instead should be using service (now action) calls instead.

Am closing as this is not something I will strive to fix but if by coincidence it works again in the future (mostly by change) then I will still note that device selection is still unsupported.
