### ISSUE TITLE
Bug: Sorting options on tables don't work

### ISSUE THREAD

**Issue by adamlc** [Sian-Lee-SA/Home-Assistant-Switch-Manager#253]
Just noticed that changing the sort options on the table doesn't appear to work on `2.0.0`

![image](https://github.com/user-attachments/assets/5f5a4b3f-ba78-4f86-9614-047d2aa766c9)

**Comment by Sian-Lee-SA** [comment]
Yh I noticed that before last release. Didn't want to dig to much into it before releasing 2.0.0 as to allow latest Home Assistant to work nicely with Switch Manger. I will investigate when I find time.

**Comment by adamlc** [comment]
Just bumping as this is going stale :)

**Comment by Sian-Lee-SA** [comment]
Removed sortable in 2.0.2, Home Assistant dev's has changed alot that the original code was relying on so it's just better to remove the option to sort and instead use the search feature. Not ideal but I don't have the time nor patrience to keep hunting down everything that the Dev's over at HA feels a ADHD twitch to change something again and again and again.

**Comment by Cyrelion** [comment]
Will this come back in the future?
