### ISSUE TITLE
Problems editing buttons

### ISSUE THREAD

**Issue by skelgaard** [Sian-Lee-SA/Home-Assistant-Switch-Manager#258]
hey,
if i go into edit a button done before 2.0
![billede](https://github.com/user-attachments/assets/5bcf5823-7f47-4098-8e9c-839b96f65b77)
then if i delete and add new actions sometimes the editor shows up, but mostly this way
![billede](https://github.com/user-attachments/assets/a4fc3eb9-811a-4b40-a5b6-fd1f14a91b01)
i see load of errors in the console
![billede](https://github.com/user-attachments/assets/05a91c20-ecf0-4df6-b50b-36b558479025)
![billede](https://github.com/user-attachments/assets/f8d225ff-f4d0-412e-b19f-c2e2411e75bc)

any suggestions is wery welcome

**Comment by Sian-Lee-SA** [comment]
I guess you missed the warning up the top of the readme? _"The device sequence action is currently unsupported, use service/action calls instead as this should be used thoughout Home Assistant anyway."_.

**Comment by skelgaard** [comment]
but even with all deleted actions it still says sequence ?
![billede](https://github.com/user-attachments/assets/02cf8340-7109-4bc2-85bd-bb05525f14f2)
and if i press add action it still stays in sequence ?

**Comment by Sian-Lee-SA** [comment]
have you hard refreshed the page? I also don't understand what "it still says sequence" means. Your screenshot shows the title sequence. That's suppose to be there, it's just empty which is normal.

**Comment by skelgaard** [comment]
![billede](https://github.com/user-attachments/assets/637884c2-1e7e-46ce-ad69-87f0a4816e46)
and yes ofcourse i have rerefshed the page, restarted home assistant and cleared cache... still giving problems for me

**Comment by Sian-Lee-SA** [comment]
Hard refresh... meaning cleared cache etc. and again, your image gives no context to your problem whatsoever

**Comment by Sian-Lee-SA** [comment]
And you're running latest versions for both HA and Switch Manager?

**Comment by skelgaard** [comment]
![billede](https://github.com/user-attachments/assets/ff229006-2a42-4e98-9b0c-02fa4ee653e5)
![billede](https://github.com/user-attachments/assets/12660cb6-ef94-4575-bd37-c972c05b2530)


https://github.com/user-attachments/assets/65c0af30-b976-468c-ae8b-e832fa235114

**Comment by Sian-Lee-SA** [comment]
Was your switch saved with the device action that you tried previously?

**Comment by skelgaard** [comment]
yes...
i have deleted all actions, saved it, closed it, reopened it....
do i need to delete the switch and readd them to make it work again ?
i would hate doing that for 20+ switches.....

**Comment by Sian-Lee-SA** [comment]
go into your HA config .storage folder and open the file switch_manager. You should see if the device action is stored in there for your switch. If you're comfortable with JSON, just go ahead and remove the device actions. Also if you do create a new switch, does adding actions work normally?

**Comment by skelgaard** [comment]
"10": {
        "name": "Marius Switch",
        "enabled": true,
        "blueprint": "zigbee2mqtt-ikea-styrbar",
        "identifier": "zigbee2mqtt/Marius switch/action",
        "variables": null,
        "rotate": 0,
        "buttons": [
          {
            "actions": [
              {
                "sequence": [],
                "mode": "single"
              },
              {
                "sequence": [
                  {
                    "action": "light.turn_off",
                    "metadata": {},
                    "data": {},
                    "target": {
                      "device_id": [
                        "739ccd74b93d10c43d2af14c5326345d",
                        "134d79bf79e0dc005900cb4778aa24b2",
                        "c903a00aa3c88b9d2491e685ec95fc5d"
                      ]
                    }
                  }
                ],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              }
            ]
          },
          {
            "actions": [
              {
                "sequence": [],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              }
            ]
          },
          {
            "actions": [
              {
                "sequence": [],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              }
            ]
          },
          {
            "actions": [
              {
                "sequence": [],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              }
            ]
          }
        ]
      },

**Comment by Sian-Lee-SA** [comment]
is the console log showing anything relevant?

**Comment by skelgaard** [comment]
![billede](https://github.com/user-attachments/assets/f31d0ea0-c4f9-489b-8479-5a5f47fafffc)
![billede](https://github.com/user-attachments/assets/21aa0db4-4784-4103-8880-6f777237e8e7)

**Comment by Sian-Lee-SA** [comment]
Also if you do create a new switch, does adding actions work normally?... I did ask before but you might've missed it as it was an edit. Also that error doesn't give me much to go on without the full message.

**Comment by skelgaard** [comment]
i delete the switch and readded it... it does the same for me

or we in a state where i need to uninstall, delete the config and install agaon ?

**Comment by Sian-Lee-SA** [comment]
I really have no idea whats going on here, It's not even guarenteed to work even if you do that. I also have not had any issue raised that is remotetly similiar to this issue. I would try a different browser first just to rule that out. Also check to make sure it works normally in your automations page when you add an action etc. Lastly you can copy the json file and back it up and try a fresh install then revert if need be

**Comment by philippnbg** [comment]
I do have the same issue.
Steps to reproduce:

1) newly added switch via UI
![image](https://github.com/user-attachments/assets/6dfad469-b4f2-443a-872b-f14ef6437ffd)

2) Add device action in init (or press, it doesn't matter)
![image](https://github.com/user-attachments/assets/d4444f50-2277-4b7b-a0b3-35da3d33db95)

3) select device --> error
![image](https://github.com/user-attachments/assets/9fa2af6b-f72d-46af-bb6e-0ee5be971799)

**Comment by skelgaard** [comment]
just did a clean install on my test homeassistant and setuo same switch... here it works fine... will try and anylyse the difference in the two config files

**Comment by skelgaard** [comment]
not working button
`          {
            "actions": [
              {
                "sequence": [],
                "mode": "single"
              },
              {
                "sequence": [
                  {
                    "action": "light.turn_off",
                    "metadata": {},
                    "data": {},
                    "target": {
                      "device_id": [
                        "739ccd74b93d10c43d2af14c5326345d",
                        "134d79bf79e0dc005900cb4778aa24b2",
                        "c903a00aa3c88b9d2491e685ec95fc5d"
                      ]
                    }
                  }
                ],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              }
            ]
          },

working code
`          {
            "actions": [
              {
                "sequence": [
                  {
                    "action": "light.toggle",
                    "metadata": {},
                    "data": {},
                    "target": {
                      "device_id": [
                        "35353e944b4cdf3d0f1b926391938d03",
                        "0f7d5d4f54c3e74ef794a60421f5c57e",
                        "70b230fbfe8dfd634d45cd677794c588"
                      ]
                    }
                  }
                ],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              },
              {
                "sequence": [],
                "mode": "single"
              }
            ]
          },
i copied over the working code, changed the id's and started HA again and now its working

**Comment by skelgaard** [comment]
one of the others making errors
`                "sequence": [
                  {
                    "type": "toggle",
                    "device_id": "2b93e8dbd0349e86e005acc332759824",
                    "entity_id": "8315260bc642d44f90a85caf70cce427",
                    "domain": "light"
                  }
                ],
`

**Comment by philippnbg** [comment]
> I do have the same issue. Tested on multiple browsers, no browser-plugins present. homeassistant and switch-manager on latest version.
> 
> Steps to reproduce:
> 
> 1. newly added switch via UI
>    ![image](https://private-user-images.githubusercontent.com/22637680/367614637-6dfad469-b4f2-443a-872b-f14ef6437ffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0Mjg0NzgsIm5iZiI6MTcyNjQyODE3OCwicGF0aCI6Ii8yMjYzNzY4MC8zNjc2MTQ2MzctNmRmYWQ0NjktYjRmMi00NDNhLTg3MmItZjE0ZWY2NDM3ZmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE5MjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYWY3Mzk5YTQ0YzgzOTQwYjYyOTI0MDM3ODM4MzUzYjk1MTgyMmI2ZWNjOWFjNjUxOGQwZTdhZWM1YTg4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bA5XL7o72j1Q2EMCEgSJcYRtFoupSLLLPdzjFI7ipVY)
> 2. Add device action in init (or press, it doesn't matter)
>    ![image](https://private-user-images.githubusercontent.com/22637680/367614693-d4444f50-2277-4b7b-a0b3-35da3d33db95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0Mjg0NzgsIm5iZiI6MTcyNjQyODE3OCwicGF0aCI6Ii8yMjYzNzY4MC8zNjc2MTQ2OTMtZDQ0NDRmNTAtMjI3Ny00YjdiLWEwYjMtMzVkYTNkMzNkYjk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE5MjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNjRmNjBjMzhhMWQyZjgwYzdiMjk2YzE4MTQwM2I2Mjc4YTEzYjc2NzJjNTFjOWFjZTJkNTA1YzM5ZGIyMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bmfMC9HlbHqAWwk319KoGzMHlgdMfxeD3hv3UT11Tw8)
> 3. select device --> error
>    ![image](https://private-user-images.githubusercontent.com/22637680/367614739-9fa2af6b-f72d-46af-bb6e-0ee5be971799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0Mjg0NzgsIm5iZiI6MTcyNjQyODE3OCwicGF0aCI6Ii8yMjYzNzY4MC8zNjc2MTQ3MzktOWZhMmFmNmItZjcyZC00NmFmLWJiNmUtMGVlNWJlOTcxNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE5MjI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljN2YzN2IxZDRkMjZkNmM5YTFiYzNmMTJhMTI1NzZiM2E1NGY2ZTg1NzJmZDc0YWExYzE0ZjY1MzM4Yzg2ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rxmcbi-RPyyb6bvfBSxO8X1bMlUd1ox7AS4m0AaM-EM)

Oh boi. It took me a while to actually understand what @Sian-Lee-SA ment with _The device sequence action is currently unsupported, use service/action calls instead as this should be used thoughout Home Assistant anyway_

For everyone else that didn't RTFM:
direct references to the device are currently not possible.
In my case I wanted check a condition based on the state of a referenced device. Instead i should check the condition of the entity
![image](https://github.com/user-attachments/assets/6efc9b2f-8665-42d2-bee6-1cb371dd966d)

**Comment by skelgaard** [comment]
thats fine, but shouldn't it automatic convert it to that when i updated from 1.* to 2.* ?
else there is no other way than to start with a clean config and do it all again......
