### ISSUE TITLE
Ikea Styrbar error HomeError in describing action: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by owangen** [Sian-Lee-SA/Home-Assistant-Switch-Manager#260]
I'm new to switch manager and have an Ikea Styrbar I'm trying to configure, but I'm getting the error "HomeError in describing action: undefined is not iterable (cannot read property Symbol(Symbol.iterator))".
I'm doing the following:

1. Choose Zigbee2MQTT - Ikea Styrbar
2. Create a sequence
3. Add Action
4. Choose Unit
5. Finding the light that I want to control.
6. The error comes up

I can choose action and then Light. E.g turn off and on, that works, but I want to be able to dim the light I'm controlling.

**Comment by Sian-Lee-SA** [comment]
Closing as duplicate. You can dim with the action light.turn_on and brightness steps.
