### ISSUE TITLE
Calling service or scripts doesn't work

### ISSUE THREAD

**Issue by michalg-** [Sian-Lee-SA/Home-Assistant-Switch-Manager#264]
Hey, I'm having trouble running a script or a TTS action through the creator in Switch Manager. I have a very simple script:
```script.yml
action: chime_tts.say
data:
  chime_path: bright
  tts_speed: 121
  tts_platform: google_translate
  cache: true
  language: pl
  message: Okej gaszę!
  volume_level: 0.7
target:
  device_id: 21dcd3d44fc1667886f82ea27ab51fd8
```

And it works in the developer console, but when I try to add it to a button action like:
```sm.yml
- action: script.okej_gasze
- action: light.turn_off
  target:
    entity_id:
      - light.zarowka_jajko
```

I get an error in the console:

```console.log
2024-10-08 19:25:59.600 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [3212426736] Error handling message: extra keys not allowed @ data['action']. Got {'action': 'script.okej_gasze', 'metadata': {}, 'data': {}} (invalid_format) Michal from 172.69.155.169 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15)
```

What am I doing wrong or what's the solution to this problem?

**Comment by Sian-Lee-SA** [comment]
What version of HA and Switch Manager are you running?

**Comment by michalg-** [comment]
HA Core: 2024.11.0.dev202410090229
Switch Manager: v2.0.0

I solved this problem moving actions to a automation and just call it on button press, but I think it should also work defining in the regular way.

**Comment by Sian-Lee-SA** [comment]
Works fine for me

**Comment by michalg-** [comment]
Right, I forgot that I'm using the dev branch. Anyway, it looks like the issue is only related to the TTS actions, as all the others are executed as expected.

**Comment by Sian-Lee-SA** [comment]
Stange, TTS has been flakey for me in general throughout HA. Will see how things goes once a stable release is out etc and whether needs further investigating.

**Comment by michalg-** [comment]
@Sian-Lee-SA I downgraded to stable `2024.10.1` and still reciving the same error:
```error.log
2024-10-10 09:29:37.679 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [3046419736] Error handling message: extra keys not allowed @ data['action']. Got {'action': 'automation.trigger', 'metadata': {}, 'data': {'skip_condition': True}, 'target': {'entity_id': 'automation.zgas_dol'}} (invalid_format) Michal from 192.168.68.103 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2024.9.2 (io.robbie.HomeAssistant; build:2024.881; macOS 14.7.1) Mobile/HomeAssistant, like Safari)
```
It's action for holding WXKG01LM button:
![Screenshot 2024-10-10 at 09 31 54](https://github.com/user-attachments/assets/a877fc1e-3184-416e-a50e-9ecb2e0749fd)

The error appears when I press 'Run' in the visual editor and also when I'm pressing button.

Also automation is pretty straightforward:

```automation.yaml
alias: Zgaś światło na dole
description: ""
triggers: []
conditions: []
actions:
  - action: chime_tts.say
    data:
      chime_path: hail
      volume_level: 0.75
    target:
      entity_id: media_player.lenovo_cd_18781y
  - action: light.turn_off
    target:
      area_id:
        - kuchnia
        - salon
        - lazienka
        - przedpokoj
    data: {}
mode: single
```

**Comment by Sian-Lee-SA** [comment]
I can't seem to replicate your issue, I just did
```yaml
action: automation.trigger
metadata: {}
data:
  skip_condition: true
target:
  entity_id: automation.christmas_lights_outside
```
and works fine, using run from web ui

**Comment by Sian-Lee-SA** [comment]
I also find it strange that you mention the issue is "also when I'm pressing the button." when the error log message relates to the UI and HTTP which the backend doesn't use when processing the button.
