### ISSUE TITLE
No action configurable

### ISSUE THREAD

**Issue by therxavi** [Sian-Lee-SA/Home-Assistant-Switch-Manager#266]
I have this message so i can't add any action

 Error in describing action: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

**Comment by nephrotranz** [comment]
Same problem here for already existing actions.

**Comment by Sian-Lee-SA** [comment]
Closing as duplicate https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/252
