### ISSUE TITLE
Add a new Blueprint for Homematic HM-RC-Dis-H-x-EU

### ISSUE THREAD

**Issue by Stephan-4711** [Sian-Lee-SA/Home-Assistant-Switch-Manager#267]
Hi,

I was trying to add this Remote for a new blueprint.
HM-RC-Dis-H-x-EU
[https://media.elv.com/pdsquare/140909_f01_gehomematic.jpg]

But I don't know how to handle the thing with the coordinates, because there is only one button and how to do a work around?
Any Suggestions?

**Comment by Sian-Lee-SA** [comment]
You need to work with the data supplied by the service you're using. View the data whether its MQTT or Event Bus and build your blueprint conditions based on that. If unsure, study other made blueprints and it should enlighten
