### ISSUE TITLE
IKEA Symfonisk Remote some buttons not working

### ISSUE THREAD

**Issue by hesspoint** [Sian-Lee-SA/Home-Assistant-Switch-Manager#268]
I have the new Ikea Remote the one with buttons on Zigbee2MQTT.

I have it configured in Switch Manager for quite a while and evrything was working perfectly. Recently I noticed that the 2 free buttons it the 1 and 2 dots on them do not work anymore (as said worked perfectly before).

I went into Switch Manager to check the config. I noticed that if I press a button (e.g. play) it lights up green in the UI for a sec to show that it was pressed. That works for all buttons but the 2 dot buttons. It seems they are not recognized at all.

Not sure if that is an issue with Z2M or Switch Manager.

**Comment by Sian-Lee-SA** [comment]
You will need to compare what comes through MQTT (using MQTT Explorer or something similar) and the blueprint for the switch.

**Comment by hesspoint** [comment]
ah ok thanks. I checked and in fact the buttons were not triggering anything in Z2M. I deleted the device in Z2M and added it back and now it works again. Strange. 

Anyhow thanks!
