### ISSUE TITLE
Idea: Hide device_id

### ISSUE THREAD

**Issue by noxhirsch** [Sian-Lee-SA/Home-Assistant-Switch-Manager#27]
I think the Switch Manager is an absolutely amazing UI, especially for beginners - thank you very much for creating it! The only thing that I think is not so relevant for beginners to be shown all the time is the cryptic device_id - especially since it is usually only set once.

To hide it, I have two ideas I want to suggest:
For both ideas create an entry in the menu (I replaced "disable" because I didn't know how to add an entry in the browser dev tools)
![image](https://user-images.githubusercontent.com/30938717/209561426-64a87aec-4156-4352-8e56-110e03385baf.png)

1. When you create a new switch or click on the menu entry, this dialog pops up with a description (again I wasn't able to add it with dev tools) something like "This is the configured device id. You can change it manually or by clicking on 'FIND DEVICE' and then pressing a button on the device". The usage of 'FIND DEVICE' could be followed by a "waiting-for-a-button-press-dialog" and a "success---this-is-your-new-device-id-dialog". 
![image](https://user-images.githubusercontent.com/30938717/209561248-0319d8da-279f-4387-8eef-2dc444ec1826.png)
2. A not-as-neat but maybe easier solution is to toggle the visibility of the existing device_id box with the menu entry. The input box would be hidden by default except after creating a new switch.

I'd be happy if you consider the idea, but can of course understand if you say it's too much work for a rather small change, or you just don't like the idea ;)

**Comment by Sian-Lee-SA** [comment]
There's a couple of issues. Issue one is creating extra dialogs and callbacks etc is not so straight forward, while I can do it, the trade off wouldn't be worth it which also goes to my next point.

device_id is only specific for certain services. When using MQTT or other services then the indentifier will be different. I also find it's relevant to have some kind of id visible near a title as this helps confirm that they're married (you'll be surprised how many times I've personally spent hours trying to figure out somewthing when it's just a matter of a mismatch, this of course is generalising) but I did try not to make it in your face either so kept the identifier in the top left as to not be so obvious but it should be visible for quick reference just like an entity id.

**Comment by Sian-Lee-SA** [comment]
But I do appreciate the feedback regardless and if I find others seeing this being an issue then I will try to compensate and make users happy but atm I think it's fine how it is unless for some reason it has caused mass confussion or bad user experience.

**Comment by noxhirsch** [comment]
Thanks for the explanation - I now agree that the current state is probably more useful than hiding the identifier! I'll close this issue - if it turns out that it is a relevant issue for users, it could be opened again.
