### ISSUE TITLE
How to intigrate a rotation dimmer like IKEA ICTC-G-1

### ISSUE THREAD

**Issue by TylonHH** [Sian-Lee-SA/Home-Assistant-Switch-Manager#271]
Hey,

I'm trying to add my 1st device. I just can rotate: IKEA [ICTC](https://www.zigbee2mqtt.io/devices/ICTC-G-1.html)

So I looked into the mqqt listener and I saw this

```
Nachricht 499 empfangen auf zigbee2mqtt/IKEA Drehschalter 1/action um 20:09:

brightness_move_up
```
The normal payload looks like this
```
Nachricht 500 empfangen auf zigbee2mqtt/IKEA Drehschalter 1 um 20:09:

{
    "action": null,
    "battery": 74,
    "brightness": 255,
    "last_seen": "2024-11-02T20:09:47+01:00",
    "level": 255,
    "linkquality": 75,
    "rate": 70,
    "update": {
        "installed_version": 587367985,
        "latest_version": 587367985,
        "state": "idle"
    },
    "update_available": null
}
```

I red in the manual here that I dont have to use the action adress?!
I choosed the zigbee2mqtt-lutron-auroradevice as reference since it also can rotate, but then I'm lost. What action do I use? Where is the left/right rotation recognized?

kind regards

**Comment by Sian-Lee-SA** [comment]
Not sure what you mean by "I red in the manual here that I dont have to use the action adress?!"... Eitherway, keep your MQTT monitoring app open then watch the payload when you changfe the dial and buttons etc then build a blueprnt based on those values
