### ISSUE TITLE
Actions do not work

### ISSUE THREAD

**Issue by Typ1er** [Sian-Lee-SA/Home-Assistant-Switch-Manager#273]
with the actions, no condition becomes true. My lights are on. f I use the whole thing in the automations, the query works.

![Bildschirmfoto 2024-11-02 um 23 56 48](https://github.com/user-attachments/assets/8082dbf3-6ad5-42e4-8b25-f806f89619a8)

**Comment by Sian-Lee-SA** [comment]
Does it work when running without using the UI?

**Comment by Sian-Lee-SA** [comment]
Does it also work in an automation?

**Comment by Sian-Lee-SA** [comment]
Just tried to replicate your issue but conditions work fine for me

**Comment by Typ1er** [comment]
I have reconfigured the switch. Now everything runs fine.

It could be that I changed something manually in the yaml configuration before.

**Comment by oveand** [comment]
Odd, I'm actually in the total same situation right now.
Conditions are not passing in Switch Manager while they can/will pass anywhere else.

Switch Manager:
![billede](https://github.com/user-attachments/assets/df0199e6-452f-4c23-9c14-6279d63caf70)

Regular script. Yaml is copied from switch manager to script:
![billede](https://github.com/user-attachments/assets/07dbff64-bf43-44ee-afc1-3bc696d94c6a)

**Comment by Sian-Lee-SA** [comment]
When you say they're not passing, is that just in the UI or also when executed naturally?

**Comment by oveand** [comment]
Also when executing. Enabling debug messages prints

```
Uncaught (in promise) 
Object { code: "invalid_format", message: "extra keys not allowed @ data['condition']. Got {'condition': 'state', 'entity_id': 'light.kokken_lys_kokkeno_light', 'state': 'off'}" }
​
code: "invalid_format"
​
message: "extra keys not allowed @ data['condition']. Got {'condition': 'state', 'entity_id': 'light.kokken_lys_kokkeno_light', 'state': 'off'}"
​
<prototype>: Object { … }
[switch_manager_panel.js:1:3130267]
```

**Comment by Sian-Lee-SA** [comment]
You didn't answer my question

**Comment by oveand** [comment]
Testing a second time, it does perform as expected when initiating the button physically, only in UI this is not passing.

**Comment by Sian-Lee-SA** [comment]
Ok, aslong as the button is executing naturally then its not a biggie... As the UI code is alll derived from the Home Assistant Frontend Repo I can't really delve too much into it but if there's an obvious solution then I'll revisit. But like I said, I couldn't reproduce this either. If you truely need to test a condition in the UI for some reason, then you could call a script instead or just test in the template development tools section.
