### ISSUE TITLE
Add Blueprint for Philips Hue Wall Switch Module over Z2M and ZHA.

### ISSUE THREAD

**Issue by MaxR8684** [Sian-Lee-SA/Home-Assistant-Switch-Manager#275]
Is it possible to add the Philips Wall Switch Module over Z2M and ZHA?

Not the one with two buttons but the one without buttons thats installed in the wall.

**Comment by Sian-Lee-SA** [comment]
Feel free to make one 😄, blueprints are community supplied from whom owns and tested the devices with their blueprints.
