### ISSUE TITLE
"actions" for Aqara E1 mini switch single button variant

### ISSUE THREAD

**Issue by rhuba8324** [Sian-Lee-SA/Home-Assistant-Switch-Manager#283]
_Originally posted by @Sian-Lee-SA in https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/128#issuecomment-1560138452_

Aqara E1 mini switch (WXKG20LM) is now reporting actions as 'single' instead of 'button_1_single' in Z2M.
It's been a while so I don't remember what specific update did this, but the switch is now reporting 'single' 'double' 'hold' 'release' normally just like what is documented on Z2M's page.
Thus I believe 'zigbee2mqtt-aqara-e1-wireless-mini-switch' can now be deleted, since 'zigbee2mqtt-aqara-wireless-mini-switch' now work for this variant.

![image](https://github.com/user-attachments/assets/9e12853c-6ce8-45f5-b362-96e9be16a487)
![image](https://github.com/user-attachments/assets/7ac41d52-1af1-44b4-8ee0-4298d77f89c4)

**Comment by Sian-Lee-SA** [comment]
As blueprints are community based, The repo will only update when a user updates the blueprint that they own and have tested.
