### ISSUE TITLE
Help with blueprint needed

### ISSUE THREAD

**Issue by MaxR8684** [Sian-Lee-SA/Home-Assistant-Switch-Manager#286]
Hi there,

i tried to add a blueprint for the Phillips Hue Wall switch Module via Z2M but iam struggling to get it running.

my blueprint is as following:

```
name: Philips Hue Wall Switch
service: Zigbee2MQTT
event_type: mqtt
mqtt_topic_format: zigbee2mqtt/+/action
info: Actions HOLD and HOLD (RELEASED) will only work in rocker mode.
buttons:
    actions:
      - title: init
        conditions:
          - key: type
            value: left_press
      - title: press
        conditions:
          - key: type
            value: left_press_release
      - title: hold
        conditions:
          - key: type
            value: repeat
      - title: left_hold
        conditions:
          - key: type
            value: long_release

```

But when i try to auto discover, nothing happens.

This is what i get by scanning with the mqtt Tool:

zigbee2mqtt/Philips Hue Wall Switch 3/action', payload 'left_press_release'"

**Comment by Sian-Lee-SA** [comment]
firstly there's already a blueprint for that (https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/blob/master/custom_components/switch_manager/blueprints/zigbee2mqtt-philips-hue-wall-switch-module.yaml), secondly I dont see the buttons being entered as a list, thirdly the key is payload, not sure where you got 'type' from

**Comment by MaxR8684** [comment]
firstly there are two Philips Hue Wall Switch Modules, one is surface mounted, the other one (in my case) is flush mounted. Should have made that more clear.

secondly the one i am trying to make has no buttons, it has 2x2 wires the close a contact by pressing a physical switch.

thirdly thx for your hint with the key beeing payload, that did the magic.

**Comment by Sian-Lee-SA** [comment]
yes but buttons having only one is still buttons[0] of a list of 1. If it works as not being defined as a list then that has suprised me as I must've added a type check incase an author just happens to neglect the root structure defined in the read me https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/blob/master/custom_components/switch_manager/blueprints/zigbee2mqtt-philips-hue-wall-switch-module.yaml. as under buttons key it clearly states list.
