### ISSUE TITLE
Zigbee2MQTT: Senic Friends of Hue Switch

### ISSUE THREAD

**Issue by dennisoderwald** [Sian-Lee-SA/Home-Assistant-Switch-Manager#288]
Hello,

is there a specific reason why the Senic Friends of Hue Switch is not also available with Zigbee2MQTT? It is already available under Philips Hue.

I have seen that the EnOcean (PTM 215Z) exists and that it also works with it. However, I am missing the options for Hold and Hold (Released) in the blueprint. Because this is definitely supported.

And would it be possible to add it?

Thanks for your hard work!

**Comment by Sian-Lee-SA** [comment]
> is there a specific reason why the Senic Friends of Hue Switch is not also available with Zigbee2MQTT?

Sure, because no one has made a PR for it.

https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager?tab=readme-ov-file#blueprints if you wish to create a blueprint for it.
