### ISSUE TITLE
Request - Add Paulmann 501.34 switch

### ISSUE THREAD

**Issue by sphings79** [Sian-Lee-SA/Home-Assistant-Switch-Manager#292]
Hi,

would be nice to have the Paulmann 501.34 switch (z2m).
https://de.paulmann.com/p/wandschalter-smart-home-zigbee-3.0-on-off-dimm-weiss/50134

Picture of the switch:
https://content.paulmann.com/thumbnail/95/49/c8/1635710958/50134fr01_1160x1160.jpg

Can you add it?

The actions will be:
Top left: on_1
Top right: on_2
Bottom left: off_1
Bottom right: off_2

Do you need any more informations?

regards

sphings

**Comment by Sian-Lee-SA** [comment]
Closing as duplicate https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/issues/275. Will look into making an issue disclaimer to make this more apparent

**Comment by sphings79** [comment]
Is there a tutorial for creating/adding the product?Am 22.11.2024 um 21:28 schrieb Sian ***@***.***>:﻿
Closed #292 as completed.

**Comment by Sian-Lee-SA** [comment]
https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager?tab=readme-ov-file#blueprints

**Comment by ceear** [comment]
https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/pull/307
