### ISSUE TITLE
Zigbee2Mqtt 2.0.0

### ISSUE THREAD

**Issue by jonalbr** [Sian-Lee-SA/Home-Assistant-Switch-Manager#298]
Hi,
are you planning to support zigbee2mqtt 2.0.0? Currently switch manager is relying on lagacy triggers I think. These will be removed and only events can be used. I may be totally mistaken here and there may be no change needed. 

https://github.com/Koenkk/zigbee2mqtt/discussions/24198

Sincerely Jonas

**Comment by Sian-Lee-SA** [comment]
All blueprints supplied by the community has been told to make sure Z2M isn't using legacy features so no, legacy isn't being used. Also Switch Manager doesn't "rely" on legacy features, the blueprints define how it interprets the data coming in, there could literally be a blueprint supporting legacy and one not if that's how a blueprint is defined, it's not up to switch manager. The blueprints also doesn't use Home Assistants bindings for switches, they simply use directly from the MQTT topics so Home Assistant events and triggers doesn't apply.
