### ISSUE TITLE
Preparation for Z2M 2.0.0 - Ikea switch don't respond anymore, and can't be detected

### ISSUE THREAD

**Issue by pbn42** [Sian-Lee-SA/Home-Assistant-Switch-Manager#302]
Hi,

I tried to change my Z2M configuration as recommanded here, to prepare for future Z2M 2.0.0 version :

> advanced:
>   homeassistant_legacy_entity_attributes: false
>   homeassistant_legacy_triggers: false
>   legacy_api: false
>   legacy_availability_payload: false
> device_options:
>   legacy: false
> 

But when i restarted Z2M after change, none of my remotes (mainly IKEA TRÅDFRI) respondes anymore.
When i tried to add a new one, the "auto discover" button didn't found anything.

I didn't found any log to show, but if i can help in any way.

Thanks in advance.

**Comment by Sian-Lee-SA** [comment]
You will need to comapre the MQTT data coming in and the blueprint for the switch and update it accordingly to reflect the changes in MQTT.

**Comment by pbn42** [comment]
Ok, I observed MQTT datas (using MQTT Explorer) before and after :

Before :

Topic : zigbee2mqtt/myremote
Payload :
{
  "action": "brightness_down_click",
  "battery": 40,
  "last_seen": "2024-12-10T09:07:51.399Z",
  "linkquality": 76,
  "update": {
    "installed_version": 604241925,
    "latest_version": 604241925,
    "state": "idle"
  },
  "update_available": null
}

Topic : zigbee2mqtt/myremote/action
Payload : brightness_down_click

After the update :

Topic : zigbee2mqtt/myremote
Payload :
{
  "action": "brightness_down_click",
  "battery": 40,
  "last_seen": "2024-12-10T09:24:16.854Z",
  "linkquality": 76,
  "update": {
    "installed_version": 604241925,
    "latest_version": 604241925,
    "state": "idle"
  }
}

And more importantly : NO MORE zigbee2mqtt/myremote/action topic

I'm trying to adapt the blueprint

**Comment by pbn42** [comment]
Ok, nailed it !

To get the MQTT Discovery Topic: zigbee2mqtt/+/action, you HAVE TO add this to your configarution.yaml file on MQTT : 

`
homeassistant:
  experimental_event_entities: true
`

Thanks a lot !

**Comment by Sian-Lee-SA** [comment]
I would've assumed that the action sub topic would have nothing todo with home assistant and is just how Z2M works in general. I personally don't think the dev has commincated the changes very well at all nor do I understand how or why action sub topic is no longer valid when Z2M can be used without Home Assistant and people would use that topic as default. Glad it's working, will probably have to document that option for Z2M users

**Comment by mundschenk-at** [comment]
The reason it is not in the docs because there is no link between that option and the `action` topic. Not sure what was going on for @pbn42, but the `action` topic is not deprecated and has not been removed. `homeassistant.experimental_event_entities` is only ever read in the `homeassistant` extension and has no bearing on generated state payloads.

**Comment by pbn42** [comment]
For the complete history, i removed this entry from my config (because it is said in the Z2M post : Entity attributes (homeassistant.legacy_entity_attributes setting) has been removed. This means that entities discovered by Zigbee2MQTT will no longer have entity attributes (Home Assistant entity attributes are accessed via e.g. states.binary_sensor.my_sensor.attributes). )

homeassistant:
  legacy_entity_attributes: true

That's the thing that made all my buttons unresponsive.

And when i looked why, i saw that the /action topic wasn't there anymore

**Comment by mundschenk-at** [comment]
That's a weird hiccup in your broker then, `legacy_entity_attributes` also has not got anything to do with the `action` topic.
