### ISSUE TITLE
Support for calculating long press, and double tap for Keyboard Remote

### ISSUE THREAD

**Issue by lanrat** [Sian-Lee-SA/Home-Assistant-Switch-Manager#31]
Hello,

I've just started using this integration to help me manage my automations for the [Keyboard Remote](https://www.home-assistant.io/integrations/keyboard_remote/) events. This component makes it so much easier to program the buttons!

However, the Keyboard Remote events only produce `key_down` and `key_up` events. In my automations I have logic to detect a long press and double tap by comparing the time differences between these events. Would it be possible to get some basic long and double press logic integrated for sources that may not natively support it?

I don't think it should be too difficult. A naive solution could be to maintain an in-memory map of recent button press events with timestamps and compare new incoming events to see if there is a long press (time delta between `key_down` and `key_up` > threshold) or double tap (time delta between two `key_up` events < threshold).

Thoughts?

**Comment by Sian-Lee-SA** [comment]
I'll have a look into this down the line once the integration is developed maturely and evolved but is not currently on the road map. The back end of switch manager is to do little processing and no logic apart from conditions to ensure the right button and action is pushed... As of now I let it up to the actions and sequences to handle that logic. For example, I have zwave touch devices that sends a hold event every 100ms or so which meant I had to add a wait action to give enough time for the next scene to activate for that hold event... The question ends up to how much involvement does a middle man service interoperate a device which wasn't designed with those events in mind... More so, it would make more sense to have the integration implement this
