### ISSUE TITLE
Allow reloading Blueprints without restart

### ISSUE THREAD

**Issue by lanrat** [Sian-Lee-SA/Home-Assistant-Switch-Manager#32]
Would it be possible to support reloading switch blueprints without restarting all of Home Assistant?

While experimenting and creating blueprints it can be incredibly slow to need to restart Home Assistant to test every change.

I suspect the component could selectively reload its own blueprints , and expose an option to do that in the UI?

**Comment by Sian-Lee-SA** [comment]
Reloading without restart is on the road map, currently still beta and only v0.2.6 atm

**Comment by Sian-Lee-SA** [comment]
Reload service added [v0.2.8](https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager/releases/tag/v0.2.8)
