### ISSUE TITLE
Error in Switch Manager sidebar

### ISSUE THREAD

**Issue by kenny-f** [Sian-Lee-SA/Home-Assistant-Switch-Manager#34]
There is a javascript error when I click on the sidebar. 

<img width="690" alt="image" src="https://user-images.githubusercontent.com/1841819/210106805-7a2064ce-7329-496f-9fdb-c749adda216e.png">

Looks like the iconList is not closed 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/1841819/210106874-a5fd374f-c649-415c-94ba-8205188960f4.png">

**Comment by kenny-f** [comment]
It looks like when I copied the files over it truncated that javascript file. I can see there are double the amount of lines in the original downloaded file. 

Closing.

**Comment by Sian-Lee-SA** [comment]
No problems, I was just investigating and I was about to ask if that was the end of the file, glad it's sorted

**Comment by kenny-f** [comment]
found and installed it from HACS. 
didn't see it mentioned in the documentation though

**Comment by Sian-Lee-SA** [comment]
Didn't see what mentioned in the documentation?

**Comment by kenny-f** [comment]
that you could install it from hacs, instead of downloading, then copying over the files

**Comment by Sian-Lee-SA** [comment]
I don't actually personally use hacs so I don't know the method but the first thing on the readme has HACS|Default
