### ISSUE TITLE
Add configuration option for the integration to add the plattforms used

### ISSUE THREAD

**Issue by Bascht74** [Sian-Lee-SA/Home-Assistant-Switch-Manager#46]
Hi, 

I am just starting with your custom component and I really like it. 
It is just something that I was thinking off (have a graphical user interface for buttons within HA), but I am no programmer so it was just a dream ... that came true now...

Just one idea right a the beginning. 
Can you add a config dialog where you can select the plattforms that you are using so that the list gets filtered:
- deCONZ
- Google Nest
- Homematic
- Philips Hue
- ZHA
- Zigbee2MQTT
- ZWave JS

So normally you are not using ZHA and Zigbee2MQTT --> Just disable the one you are not using...

**Comment by Sian-Lee-SA** [comment]
This will be looked at soon enough, I'm thinking of just having a search filter up top

**Comment by Sian-Lee-SA** [comment]
Services also doesn't mean it's Home Assistant integrations do doing a filter on whats not active is not possible

**Comment by Bascht74** [comment]
I think about a configuration, where you can select, what you are using (during setup of the integration or afterwards)
with that information your integration can show only what the user is using.

**Comment by Sian-Lee-SA** [comment]
I don't mind that idea but I can also imaging people setting up the integration and selecting some services then forget about it then adds a new integration later on and can't find what they're looking for. Secondly, being able to see what blueprints are made and what switches are available can help people decide on a future purchase for a switch while also finding a switch that matched the look they're after. I deliberate on it
