### ISSUE TITLE
Feature Suggestion - Per Switch Device

### ISSUE THREAD

**Issue by alec-hs** [Sian-Lee-SA/Home-Assistant-Switch-Manager#56]
It would be great to be able to define "global" device within each switch.

For example configuring a Hue Dimmer Switch you could select the single light or light group that would be used across the switch actions and accessed using some kind of variable. 

This would allow for quicker initial configuration of a switch and also be great for setting up multiple switches with all the same actions but different devices.

**Comment by Sian-Lee-SA** [comment]
I did think about device variables and this is on the roadmap

**Comment by Sian-Lee-SA** [comment]
I would probably have to implement the yaml editor for the whole structure or build a custom variable builder which honestly, I wish Home Assistant had

**Comment by alec-hs** [comment]
Yeah exposing the yaml editor would be a good mid step as we could copy paste, find replace etc.
