### ISSUE TITLE
UI configurable MQTT base topic

### ISSUE THREAD

**Issue by ufu-** [Sian-Lee-SA/Home-Assistant-Switch-Manager#60]
It would be great to have the MQTT base topic linked to a variable and configurable in the UI. 
In the current state, If using something different than the default (E.G. zigbee2mqtt for z2mqtt ) in the integration, it is not really practical to use any of the default blueprints as the aforementioned base topic gets reset to default on every update.

**Comment by Sian-Lee-SA** [comment]
I don't quite understand what you mean? MQTT topic and sub topic etc is already being passed in a variables

**Comment by Sian-Lee-SA** [comment]
You can also use this in the blueprint conditions or inside your action sequences

**Comment by Sian-Lee-SA** [comment]
For custom blueprints that you don't want overriden, you would make a custom blueprint and name it unqiue, this has been noted in the README

**Comment by ufu-** [comment]
Hello again, 
I mean the first part of this in the blueprint:
 
mqtt_topic_format: **zigbee2mqtt**/+/action

In my own case my zigbee2mqtt base topic is not **zigbee2mqtt**  therefore to use any of the default blueprints I  
have to duplicate them and rename them, otherwise if I just edit the existing one it gets, rightfully so, overwritten.
Just to be clear, passing the correct topic/subtopic in the config does not work.
It's not a big deal, and if it is a lot work by all means disregard it, but it would make it more flexible.

**Comment by ufu-** [comment]
BTW,  other that that great add-on, thank you !

**Comment by Sian-Lee-SA** [comment]
Oh ok, that's strange because if you do enter it manually then it should be stored locally, that placeholder topic is really only used for descovery. I'll have a look into it. And thank you

**Comment by ufu-** [comment]
Nevermind, I just restarted HA, checked again and it does indeed work setting the right topic/subtopic in the switch config.
Sorry about that.

**Comment by Sian-Lee-SA** [comment]
All good

**Comment by ufu-** [comment]
Still it would be handy to set the discovery topic in the UI ( maybe with a default value pre-filled).
I'm closing the request, thanks again.

**Comment by Sian-Lee-SA** [comment]
That really goes against the standard. If people want to change the standard then really it's up to them to compensate... Put it this way, if you want to set the discovery topic from the UI then the amount of time it took to do that you may aswell type it in as full
