### ISSUE TITLE
 Zooz ZEN34 - Question

### ISSUE THREAD

**Issue by lensherm** [Sian-Lee-SA/Home-Assistant-Switch-Manager#65]
Do you by chance know if a Zooz ZEN34 blueprint is going to be added?

**Comment by lensherm** [comment]
Just tried with the existing one for Zooz ZEN71 and in preliminary testing it seems to be working with ZEN34

**Comment by Sian-Lee-SA** [comment]
Blueprints are created and added via community. If you wish to make the blueprint then I'll be happy to add it 👍

**Comment by lensherm** [comment]
Thanks @Sian-Lee-SA. I'll take a look into making the blueprint.

**Comment by cameronkelley** [comment]
@lensherm - FYI, I just tested the Zen77 switch type and 1-5x taps are all working on top and bottom paddles.
When I have some time, I'll take a look at it and submit a PR specifically for the Zem34.
