### ISSUE TITLE
Zigbee2MQTT / TuYa 2 Gang Remote buttons are not rendered

### ISSUE THREAD

**Issue by mihai205** [Sian-Lee-SA/Home-Assistant-Switch-Manager#72]
Zigbee2MQTT / TuYa 2 Gang Remote
On version 0.7.0 at least, remote buttons are not rendered. See image below. The blueprint needs to change x and y to at least 1 for it to work.
![image](https://user-images.githubusercontent.com/65603209/212423449-113804b9-2554-4fc9-961c-fc64e020d94a.png)

**Comment by Sian-Lee-SA** [comment]
Ahh thanks for catching that. It's because 0 is also false. I'll change that in code

**Comment by Sian-Lee-SA** [comment]
Latest version just posted should fix this. Thanks
