### ISSUE TITLE
In Tuya 4 gang buttons zigbee2mqtt buttons are not corrected

### ISSUE THREAD

**Issue by platini76** [Sian-Lee-SA/Home-Assistant-Switch-Manager#73]
hello, blueprint for device tuya

Modello Zigbee
TS0044
Produttore Zigbee
_TZ3000_wkai4ga5

are not in correct order, can you correct?
in the meantime if you use Zignito 4 buttons it works correctly
thanks

**Comment by Sian-Lee-SA** [comment]
Yes when some companies rebrand a device generally they don't know what they're doing and change things. Currently the blueprint was tested on my _TZ3000_vp6clf9d. You can always duplicate the blueprint then rename and match to you're model... I may look into a variable for this blueprint to swap buttons around or have seperate blueprint.
