### ISSUE TITLE
switch manager don't see group in device choose..

### ISSUE THREAD

**Issue by platini76** [Sian-Lee-SA/Home-Assistant-Switch-Manager#74]
it is normal?

**Comment by Sian-Lee-SA** [comment]
Please be more specific

**Comment by platini76** [comment]
here a picture this group is not seen as lighjt
<img width="1339" alt="Screenshot 2023-01-14 alle 16 38 02" src="https://user-images.githubusercontent.com/10352902/212480153-ea9b37b7-a87c-4775-8cfa-c7ff78dd9090.png">

**Comment by Sian-Lee-SA** [comment]
The sequence editor is the same that HA uses for scripts and automations so if it's not showing then it's an issue with HA editor. You can still manually enter entity id's

**Comment by platini76** [comment]
it does not work..
<img width="1144" alt="Screenshot 2023-01-14 alle 16 47 08" src="https://user-images.githubusercontent.com/10352902/212480554-67e6f64c-e9b4-4064-bca1-295f9cc42ba0.png">

**Comment by Sian-Lee-SA** [comment]
Like I said, the issue is with Home Assistant

**Comment by platini76** [comment]
so what option I have to use to select group?

**Comment by platini76** [comment]
I discover the problem.... your app can select devices.. and not entity...
a group is an entity..
correct me if I am wrong..

**Comment by Sian-Lee-SA** [comment]
????? Just use entities and call service. Group is not a Device. Yes a group is an entity. not a device

**Comment by Sian-Lee-SA** [comment]
It's also not "my app" that you're referring to, it's HA's own component. Not switch managers

**Comment by platini76** [comment]
Sorry but I am not an expert user, don’t be severe with me.
In service there are not entities. How to make it with service? Can you kindly explain?

**Comment by Sian-Lee-SA** [comment]
Please familiar yourself with Home Assistant first before adding custom integrations as posting issues or adding on things without first knowing how to use Home Assistant is not a good idea. I've also said your issue isn't Switch Manager's issue but a Home Assistant one. I also don't know what 'severe' is in regards to the context you used it in.
