### ISSUE TITLE
Add Node ID Column to Main Page

### ISSUE THREAD

**Issue by TKpizza** [Sian-Lee-SA/Home-Assistant-Switch-Manager#76]
Can you add the node id column to the main page?
![image](https://user-images.githubusercontent.com/68114870/212731266-bf4899d4-0c72-4b36-a529-56f87109babd.png)

**Comment by Sian-Lee-SA** [comment]
I can but you need to realise that because you're using nodes, others are using different identifiers which can be pretty long and messy. I'll test it out eventually and see
