### ISSUE TITLE
double button xiaomi WXKG07LM

### ISSUE THREAD

**Issue by tontondic1980** [Sian-Lee-SA/Home-Assistant-Switch-Manager#77]
After update, xiaomi WXKG07LM no longer works

**Comment by Sian-Lee-SA** [comment]
As stated in the release notes, it had to be changed to align with the non legacy version. You just need to turn off legacy for that device as this is the standard for zigbee2mqtt. There was also an issue where the topic was matching the legacy click topic but using the action topic

**Comment by tontondic1980** [comment]
Many thanks
