### ISSUE TITLE
MQTT integration discovery

### ISSUE THREAD

**Issue by ark-** [Sian-Lee-SA/Home-Assistant-Switch-Manager#82]
Great work on the plugin.

I don't use Zigbee2MQTT but when I install this integration I get a "new integration found" for MQTT. If I click configure it asks for broker details (which I don't have). Is it possible to disable this or should I just ignore it?

**Comment by Sian-Lee-SA** [comment]
Could you try the latest release and see if it fixes this?

**Comment by ark-** [comment]
Tried now and it works great, thank you :) Fixed in V0.8.1

**Comment by Sian-Lee-SA** [comment]
Everything looks fine although the switch image is fairly small and not cropped to the edges... maybe this image would be better 
![image](https://user-images.githubusercontent.com/11685433/214208180-534f8cc6-5f8e-4e66-9de6-bef24ba4aa17.png)

Then just crop and set height to 500px
