### ISSUE TITLE
Mobile UI Issue

### ISSUE THREAD

**Issue by PepperPhil** [Sian-Lee-SA/Home-Assistant-Switch-Manager#89]
First of all many tanks for this awesome tool!

![Screenshot_20230126_195131_Home Assistant.jpg](https://user-images.githubusercontent.com/69075397/214932984-a3ae3d0d-3951-4b77-9b4c-252151a77c89.jpg)

Would be great if the UI could be adjusted a little bit for the Home Assistant Android mobile app.

**Comment by Sian-Lee-SA** [comment]
Latest version removes service and device type columns for narrow displays. This is the best that can be done

**Comment by PepperPhil** [comment]
> You must using using a very low res display. What does the automations index page look like? ![Screenshot_20230127-071930](https://user-images.githubusercontent.com/11685433/214947629-3f712f7d-d096-4f7e-901d-496959a03cff.png)

Sorry, what "automations index page" do you mean? The home assistant automation page only has the Name column on my phone. 

Regarding low res display, it is a Samsung S21 FE phone, just as FYI.

**Comment by Sian-Lee-SA** [comment]
Index pages are generally the pages that list's something in particular. In this case, your automations which also uses the same table design. I was more curious as to how much of the name it fits than the columns it's displaying. I also feel you may have set your display settings to something different than the stadard (I've had issues with samsung devices displaying webpages not in a native resolution), I have the Pixel 4 which is comparable to your device in resolution so there should be a setting somewhere (even your title and add switch is overly blown)...

Eitherway next release will show more of the name while the other columns are omitted on smaller displays
