### ISSUE TITLE
Unable to see Hue Dimmer v1

### ISSUE THREAD

**Issue by m90att** [Sian-Lee-SA/Home-Assistant-Switch-Manager#97]
Hi,

Another great tool, thank you...

After your response to my comment (Matt, 2 weeks ago) on your youtube video **(https://www.youtube.com/watch?v=m2Rlobvo5cI&t=353s)** I've tried and tried to get the v1 dimmer working but the switch manager never detects any presses.  These are the steps I've tried.

- Using Zigbee2MQTT / Philips Hue Dimmer v1/v2, autodetect finds nothing at all, after pressing all buttons, holding all buttons

![image](https://user-images.githubusercontent.com/56609577/216655897-646dab2a-f492-4966-a5c1-9808c9e5b62b.png)

- Using the MQTT Tool, the button press is seen

![image](https://user-images.githubusercontent.com/56609577/216656216-4b162d43-55ca-4668-9874-9c59f91eb298.png)

- Legacy is set to 'off' in MQTT settings, there are multiple places I can see legacy so I turned them all off first, then turned one on at a time and then restarting Zigbee2MQTT but still no change.  I tried completely restarting HA, but still no change.
Settings, Advanced tab
![image](https://user-images.githubusercontent.com/56609577/216656729-d41d8cbf-03db-4d89-86fd-7d3bb8767d46.png)

Settings, Home Assistant tab
![image](https://user-images.githubusercontent.com/56609577/216656994-9dd0e4bc-e3b9-4afe-9760-eeeab7373c66.png)

I don't know what else to try.  My v2s are working ok but I've got some v1s that I'd love to be able to use.

This is my v1
![image](https://user-images.githubusercontent.com/56609577/216657876-1ab596f5-c3e8-4781-8bcd-ad2dbf862f16.png)

Any guidance would be much appreciated if you have time.

Thanks,  Matt

**Comment by Sian-Lee-SA** [comment]
the issue I can see is that the payload you're getting is on-press when it should be on_press. You can confirm this by visiting https://www.zigbee2mqtt.io/devices/324131092621.html#action-enum and seeing the Action section. Are you using the latest Zigbee2MQTT version. If so you should be raising an issue with them as to why your action payload is on-press and not on_press etc

**Comment by Mattie432** [comment]
commenting in case it helps others, I had some V1 dimmer switches that suddenly started to publish on the legacy `on-press` topic rather than the `on_press` one. This was despite having all the global legacy settings turned off.

Each switch additionally has a legacy option available, in my case this was unset, but forcing that to 'off' fixed my issues.

![Image](https://github.com/user-attachments/assets/ad55ed7e-6b54-46bb-8993-9fe5f315a5ec)
